### ISSUE TITLE
CAN NOT RUN DEMO!

### ISSUE THREAD

**Issue by liu-jinyu** [iiau-tracker/SPLT#9]
# run demo have enourmous errors of arugument numbers
## have never met issues like this

```
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "demo.py", line 782, in <module>
    tracker = MobileTracker(vot=use_vot, dis=display)
  File "demo.py", line 93, in __init__
    model = build_man_model(model_config=model_config, is_training=False)
  File "/home/jinyu/splt/SPLT-master/core/model_builder.py", line 74, in build_man_model
    hard_example_miner) = losses_builder.build(model_config.loss)
ValueError: too many values to unpack
```
(have added one is_training in model_builder.py)
!
PYTHON27&PYTHON36 both errororororrr

**Comment by iiau-tracker** [comment]
I have tested our code again. There is no problem to run.
`(have added one is_training in model_builder.py)`  What did you mean?

**Comment by liu-jinyu** [comment]
Thank you for your response
I successfully ran your demo. Powerful Algorithm

I made a mistake that I used the >model from google. But i just noticed that you have included it in your lib path. Those packages have function of same name but different parameters.
for those have the same problem, i recomend to export the object_detection path 

```export PYTHONPATH=$PYTHONPATH:"/home/jinyu/splt/SPLT-master/lib:/home/jinyu/splt/SPLT-master/lib/slim"```
